### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by nathanqueija** [PacktPublishing/Rust-2018-Projects#1]
Hello Packtpub team and @carlomilanesi, 

When is the book going to be released?
The website says April 17h, but the book isn’t available yet.
What is the plan for the release?

Thanks and have a good day!

**Comment by 1init** [comment]
@nathanqueija i will give the useful comment of "i am in the same boat waiting on release ("

**Comment by nathanqueija** [comment]
@1init they just updated the website saying it will be released on September 11th 😢

**Comment by 1init** [comment]
Not sure that is a wise date to choose to release anything. wonder if 11/9 will the final date.

**Comment by carlomilanesi** [comment]
Hi. The books has been released, It is already available as an e-book.

**Comment by carlomilanesi** [comment]
The book is available also printed on paperback.

**Comment by nathanqueija** [comment]
Oh yes! Gonna start reading it now. Thanks @carlomilanesi
