### ISSUE TITLE
Chapter 5 Examples return blank page and no error

### ISSUE THREAD

**Issue by lorenzoreyes** [PacktPublishing/Rust-2018-Projects#3]
Just launch examples from the repository, installed cargo-web, and used commando cargo web start for the projects, there no error
when running the examples but it renders a blank page for all the projects
Tried Opera GX, Brave, Chrome and Mozilla
127.0.01:8000
localhost:8000

**Comment by carlomilanesi** [comment]
Corrected the bug, due to a new version of Yew. Please, read the README of Chapter05.
